/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.proyetogrupo.proyetofinal.apresentacao;

import com.proyetogrupo.proyetofinal.negocio.TreinoNegocio;
import com.proyetogrupo.proyetofinal.negocio.dao.ServiceFactory;
import com.proyetogrupo.proyetofinal.negocio.dao.impl.AlunoDAOImpl;
import com.proyetogrupo.proyetofinal.negocio.exceptions.BusinessException;
import com.proyetogrupo.proyetofinal.negocio.model.Aluno;
import com.proyetogrupo.proyetofinal.negocio.model.Treino;
import com.proyetogrupo.proyetofinal.persistencia.DB;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.time.format.DateTimeParseException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author pedro
 */
public class TelaTreinos extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaTreinos.class.getName());
    private TreinoNegocio treinoNegocio;
    private final List<Treino> treinosCarregados = new ArrayList<>();
    private final DateTimeFormatter dateFormatter = DateTimeFormatter.ofPattern("dd/MM/yy");


    /**
     * Creates new form TelaTreinos1
     */
    public TelaTreinos() {
        initComponents();
    // inicializa serviço de treinos
    treinoNegocio = ServiceFactory.criarTreinoService();

    // carrega combos
    carregarAlunos();
    carregarProfessores();

    // botão "Carregar treinos" do aluno
    btnCarregarTreinos12.addActionListener(e -> carregarTreinosDoAlunoSelecionado());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelAluno = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        comboAluno = new javax.swing.JComboBox<>();
        btnCarregarTreinos = new javax.swing.JButton();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        panelAluno12 = new javax.swing.JPanel();
        jLabel123 = new javax.swing.JLabel();
        comboAluno12 = new javax.swing.JComboBox<>();
        btnCarregarTreinos12 = new javax.swing.JButton();
        jPanel30 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        comboProfessor22 = new javax.swing.JComboBox<>();
        jLabel124 = new javax.swing.JLabel();
        jScrollPane23 = new javax.swing.JScrollPane();
        txtDescricao22 = new javax.swing.JTextArea();
        jLabel125 = new javax.swing.JLabel();
        txtDataInicio22 = new javax.swing.JFormattedTextField();
        jLabel126 = new javax.swing.JLabel();
        txtDataFim22 = new javax.swing.JFormattedTextField();
        btnEntrar22 = new javax.swing.JButton();
        jLabel127 = new javax.swing.JLabel();
        jComboBox23 = new javax.swing.JComboBox<>();
        jPanel31 = new javax.swing.JPanel();
        tblTreinos7 = new javax.swing.JScrollPane();
        jTable8 = new javax.swing.JTable();
        btnDesativar7 = new javax.swing.JButton();

        panelAluno.setBorder(javax.swing.BorderFactory.createTitledBorder("Dados Aluno"));

        jLabel1.setText("Aluno");

        comboAluno.addActionListener(this::comboAlunoActionPerformed);

        btnCarregarTreinos.setText("Carregar treinos");

        javax.swing.GroupLayout panelAlunoLayout = new javax.swing.GroupLayout(panelAluno);
        panelAluno.setLayout(panelAlunoLayout);
        panelAlunoLayout.setHorizontalGroup(
            panelAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAlunoLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel1)
                .addGap(51, 51, 51)
                .addComponent(comboAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(btnCarregarTreinos)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelAlunoLayout.setVerticalGroup(
            panelAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAlunoLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(panelAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(comboAluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCarregarTreinos))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        panelAluno12.setBorder(javax.swing.BorderFactory.createTitledBorder("Dados Aluno"));

        jLabel123.setText("Aluno");

        comboAluno12.addActionListener(this::comboAluno12ActionPerformed);

        btnCarregarTreinos12.setText("Carregar treinos");

        javax.swing.GroupLayout panelAluno12Layout = new javax.swing.GroupLayout(panelAluno12);
        panelAluno12.setLayout(panelAluno12Layout);
        panelAluno12Layout.setHorizontalGroup(
            panelAluno12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAluno12Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel123)
                .addGap(51, 51, 51)
                .addComponent(comboAluno12, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(btnCarregarTreinos12)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelAluno12Layout.setVerticalGroup(
            panelAluno12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAluno12Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(panelAluno12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel123)
                    .addComponent(comboAluno12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCarregarTreinos12))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        jPanel30.setBorder(javax.swing.BorderFactory.createTitledBorder("Dados Treino"));

        jLabel2.setText("Professor:");

        jLabel124.setText("Descrição:");

        txtDescricao22.setColumns(20);
        txtDescricao22.setRows(5);
        jScrollPane23.setViewportView(txtDescricao22);

        jLabel125.setText("Data início:");

        txtDataInicio22.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd/MM/yy"))));

        jLabel126.setText("Data Fim:");

        txtDataFim22.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd/MM/yy"))));
        txtDataFim22.addActionListener(this::txtDataFim22ActionPerformed);

        btnEntrar22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Square-Tick@2x.png"))); // NOI18N
        btnEntrar22.setText("Salvar");
        btnEntrar22.addActionListener(this::btnEntrar22ActionPerformed);

        jLabel127.setText("Status do treino");

        jComboBox23.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ativo", "Inativo" }));

        javax.swing.GroupLayout jPanel30Layout = new javax.swing.GroupLayout(jPanel30);
        jPanel30.setLayout(jPanel30Layout);
        jPanel30Layout.setHorizontalGroup(
            jPanel30Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel30Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanel30Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel124)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel30Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(comboProfessor22, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane23, javax.swing.GroupLayout.DEFAULT_SIZE, 340, Short.MAX_VALUE))
                .addGap(121, 121, 121)
                .addGroup(jPanel30Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel30Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel30Layout.createSequentialGroup()
                            .addComponent(jLabel125)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtDataInicio22, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel30Layout.createSequentialGroup()
                            .addComponent(jLabel126)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(jPanel30Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtDataFim22)
                                .addGroup(jPanel30Layout.createSequentialGroup()
                                    .addGap(9, 9, 9)
                                    .addComponent(btnEntrar22)
                                    .addGap(0, 0, Short.MAX_VALUE)))))
                    .addGroup(jPanel30Layout.createSequentialGroup()
                        .addComponent(jLabel127)
                        .addGap(18, 18, 18)
                        .addComponent(jComboBox23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel30Layout.setVerticalGroup(
            jPanel30Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel30Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel30Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(comboProfessor22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel125)
                    .addComponent(txtDataInicio22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel30Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel124)
                    .addComponent(jScrollPane23, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel30Layout.createSequentialGroup()
                        .addGroup(jPanel30Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel126)
                            .addComponent(txtDataFim22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel30Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel127)
                            .addComponent(jComboBox23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnEntrar22)
                .addGap(52, 52, 52))
        );

        jPanel31.setBorder(javax.swing.BorderFactory.createTitledBorder("Tabela treinos"));

        jTable8.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "CPF", "Professor", "Status", "Data Início", "Data Fim", "Descrição"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblTreinos7.setViewportView(jTable8);

        btnDesativar7.setText("Desativar treino selecionado");
        btnDesativar7.addActionListener(this::btnDesativar7ActionPerformed);

        javax.swing.GroupLayout jPanel31Layout = new javax.swing.GroupLayout(jPanel31);
        jPanel31.setLayout(jPanel31Layout);
        jPanel31Layout.setHorizontalGroup(
            jPanel31Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel31Layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(tblTreinos7, javax.swing.GroupLayout.PREFERRED_SIZE, 1081, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel31Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnDesativar7)
                .addGap(436, 436, 436))
        );
        jPanel31Layout.setVerticalGroup(
            jPanel31Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel31Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(tblTreinos7, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addComponent(btnDesativar7)
                .addGap(53, 53, 53))
        );

        jDesktopPane1.setLayer(panelAluno12, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jPanel30, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jPanel31, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelAluno12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel30, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel31, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(panelAluno12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jPanel30, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel31, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comboAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboAlunoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboAlunoActionPerformed

    private void comboAluno12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboAluno12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboAluno12ActionPerformed

    private void txtDataFim22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDataFim22ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDataFim22ActionPerformed

    private void btnEntrar22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntrar22ActionPerformed
        // TODO add your handling code here:
        salvarTreino();
    }//GEN-LAST:event_btnEntrar22ActionPerformed

    private void btnDesativar7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDesativar7ActionPerformed
        // TODO add your handling code here:
        desativarTreinoSelecionado();
    }//GEN-LAST:event_btnDesativar7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TelaTreinos().setVisible(true));
    }
    private void salvarTreino() {
    try {
        // 1. Pega CPF do aluno selecionado
        String itemAluno = (String) comboAluno12.getSelectedItem();
        if (itemAluno == null || itemAluno.isBlank()) {
            JOptionPane.showMessageDialog(this, "Selecione um aluno.", "Aviso", JOptionPane.WARNING_MESSAGE);
            return;
        }
        String cpfAluno = itemAluno.split(" - ")[0].trim(); // "12345678900 - João" -> "12345678900"

        // 2. Pega id do professor selecionado
        String itemProfessor = (String) comboProfessor22.getSelectedItem();
        if (itemProfessor == null || itemProfessor.isBlank()) {
            JOptionPane.showMessageDialog(this, "Selecione um professor.", "Aviso", JOptionPane.WARNING_MESSAGE);
            return;
        }
        int idProfessor = Integer.parseInt(itemProfessor.split(" - ")[0].trim()); // "1 - Giomar" -> 1

        // 3. Demais campos
        String descricao = txtDescricao22.getText().trim();
        String statusSelecionado = (String) jComboBox23.getSelectedItem(); // "Ativo"/"Inativo" (negócio depois força "ATIVO")

        LocalDate dataInicio = parseData(txtDataInicio22.getText());
        LocalDate dataFim = parseData(txtDataFim22.getText());

        // 4. Monta objeto Treino
        Treino treino = new Treino();
        treino.setIdAluno(cpfAluno);        // CPF do aluno (String)
        treino.setIdProfessor(idProfessor); // id numérico do professor
        treino.setDescricao(descricao);
        treino.setStatus(statusSelecionado);
        treino.setDataInicio(dataInicio);
        treino.setDataFim(dataFim);

        // 5. Chama camada de negócio
        treinoNegocio.criarTreino(treino);

        JOptionPane.showMessageDialog(this,
                "Treino salvo com sucesso!",
                "Sucesso",
                JOptionPane.INFORMATION_MESSAGE);

        // recarrega tabela do aluno atual
        carregarTreinosDoAlunoSelecionado();
        limparCamposTreino();

    } catch (DateTimeParseException e) {
        JOptionPane.showMessageDialog(this,
                "Data em formato inválido. Use dd/MM/aa.",
                "Erro",
                JOptionPane.ERROR_MESSAGE);
    } catch (BusinessException e) {
        JOptionPane.showMessageDialog(this,
                e.getMessage(),
                "Erro de validação",
                JOptionPane.WARNING_MESSAGE);
    } catch (SQLException e) {
        logger.log(Level.SEVERE, "Erro ao salvar treino", e);
        JOptionPane.showMessageDialog(this,
                "Erro ao salvar treino no banco: " + e.getMessage(),
                "Erro",
                JOptionPane.ERROR_MESSAGE);
    } catch (Exception e) {
        logger.log(Level.SEVERE, "Erro inesperado ao salvar treino", e);
        JOptionPane.showMessageDialog(this,
                "Erro inesperado: " + e.getMessage(),
                "Erro",
                JOptionPane.ERROR_MESSAGE);
    }
}
    
    private LocalDate parseData(String texto) {
    if (texto == null) return null;
    String limpo = texto.replace("/", "").trim();
    if (limpo.isEmpty()) {
        return null; // campo em branco
    }
    return LocalDate.parse(texto.trim(), dateFormatter);
}

    private void limparCamposTreino() {
    txtDescricao22.setText("");
    txtDataInicio22.setText("");
    txtDataFim22.setText("");
    jComboBox23.setSelectedIndex(0); // "Ativo"
}

    
    private void carregarAlunos() {
    comboAluno12.removeAllItems();

    try {
        AlunoDAOImpl alunoDAO = new AlunoDAOImpl(DB.getConnection());
        List<Aluno> alunos = alunoDAO.listAll();

        for (Aluno a : alunos) {
            // Exibe "CPF - Nome" no combo
            comboAluno12.addItem(a.getIdAluno() + " - " + a.getNome());
        }
    } catch (SQLException e) {
        logger.log(Level.SEVERE, "Erro ao carregar alunos", e);
        JOptionPane.showMessageDialog(this,
                "Erro ao carregar alunos: " + e.getMessage(),
                "Erro",
                JOptionPane.ERROR_MESSAGE);
    }
}

    
    private void carregarProfessores() {
    comboProfessor22.removeAllItems();

    String sql = "SELECT idProfessor, nome FROM Professor";

    try (PreparedStatement st = DB.getConnection().prepareStatement(sql);
         ResultSet rs = st.executeQuery()) {

        while (rs.next()) {
            int id = rs.getInt("idProfessor");
            String nome = rs.getString("nome");
            comboProfessor22.addItem(id + " - " + nome);
        }

    } catch (SQLException e) {
        logger.log(Level.SEVERE, "Erro ao carregar professores", e);
        JOptionPane.showMessageDialog(this,
                "Erro ao carregar professores: " + e.getMessage(),
                "Erro",
                JOptionPane.ERROR_MESSAGE);
    }
}

    
    private void carregarTreinosDoAlunoSelecionado() {
    String itemAluno = (String) comboAluno12.getSelectedItem();
    if (itemAluno == null || itemAluno.isBlank()) {
        JOptionPane.showMessageDialog(this, "Selecione um aluno.", "Aviso", JOptionPane.WARNING_MESSAGE);
        return;
    }

    String cpfAluno = itemAluno.split(" - ")[0].trim();

    try {
        treinosCarregados.clear();
        treinosCarregados.addAll(treinoNegocio.listarPorAluno(cpfAluno));

        DefaultTableModel model = (DefaultTableModel) jTable8.getModel();
        model.setRowCount(0);

        for (Treino t : treinosCarregados) {
            model.addRow(new Object[]{
                    t.getIdAluno(), // CPF
                    t.getIdProfessor(), // se quiser, depois buscamos o nome aqui
                    t.getStatus(),
                    t.getDataInicio() != null ? t.getDataInicio().format(dateFormatter) : "",
                    t.getDataFim() != null ? t.getDataFim().format(dateFormatter) : "",
                    t.getDescricao()
            });
        }

    } catch (BusinessException e) {
        JOptionPane.showMessageDialog(this,
                e.getMessage(),
                "Erro de validação",
                JOptionPane.WARNING_MESSAGE);
    } catch (SQLException e) {
        logger.log(Level.SEVERE, "Erro ao carregar treinos", e);
        JOptionPane.showMessageDialog(this,
                "Erro ao carregar treinos: " + e.getMessage(),
                "Erro",
                JOptionPane.ERROR_MESSAGE);
    }
}

private void desativarTreinoSelecionado() {
    int linha = jTable8.getSelectedRow();
    if (linha == -1) {
        JOptionPane.showMessageDialog(this,
                "Selecione um treino na tabela.",
                "Aviso",
                JOptionPane.WARNING_MESSAGE);
        return;
    }

    Treino treino = treinosCarregados.get(linha);

    try {
        treinoNegocio.finalizarTreino(treino.getIdTreino());

        JOptionPane.showMessageDialog(this,
                "Treino desativado/finalizado com sucesso!",
                "Sucesso",
                JOptionPane.INFORMATION_MESSAGE);

        carregarTreinosDoAlunoSelecionado();

    } catch (BusinessException e) {
        JOptionPane.showMessageDialog(this,
                e.getMessage(),
                "Erro de validação",
                JOptionPane.WARNING_MESSAGE);
    } catch (SQLException e) {
        logger.log(Level.SEVERE, "Erro ao desativar treino", e);
        JOptionPane.showMessageDialog(this,
                "Erro ao desativar treino: " + e.getMessage(),
                "Erro",
                JOptionPane.ERROR_MESSAGE);
    }
}


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCarregarTreinos;
    private javax.swing.JButton btnCarregarTreinos12;
    private javax.swing.JButton btnDesativar7;
    private javax.swing.JButton btnEntrar22;
    private javax.swing.JComboBox<String> comboAluno;
    private javax.swing.JComboBox<String> comboAluno12;
    private javax.swing.JComboBox<String> comboProfessor22;
    private javax.swing.JComboBox<String> jComboBox23;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel123;
    private javax.swing.JLabel jLabel124;
    private javax.swing.JLabel jLabel125;
    private javax.swing.JLabel jLabel126;
    private javax.swing.JLabel jLabel127;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel30;
    private javax.swing.JPanel jPanel31;
    private javax.swing.JScrollPane jScrollPane23;
    private javax.swing.JTable jTable8;
    private javax.swing.JPanel panelAluno;
    private javax.swing.JPanel panelAluno12;
    private javax.swing.JScrollPane tblTreinos7;
    private javax.swing.JFormattedTextField txtDataFim22;
    private javax.swing.JFormattedTextField txtDataInicio22;
    private javax.swing.JTextArea txtDescricao22;
    // End of variables declaration//GEN-END:variables
}
