/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.proyetogrupo.proyetofinal.apresentacao;

import javax.swing.JOptionPane;

/**
 *
 * @author pedro
 */
public class TelaPrincipal extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaPrincipal.class.getName());

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnPagamento = new javax.swing.JButton();
        btnTreinosInativos = new javax.swing.JButton();
        btnTreinos = new javax.swing.JButton();
        btnTreinosAtivos = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuCadastro = new javax.swing.JMenu();
        menuItemAluno = new javax.swing.JMenuItem();
        menuItemProfessor = new javax.swing.JMenuItem();
        menuTreinos = new javax.swing.JMenu();
        menuItemTreinos = new javax.swing.JMenuItem();
        menuPagamento = new javax.swing.JMenu();
        menuItemPagamentos = new javax.swing.JMenuItem();
        menuRelatorios = new javax.swing.JMenu();
        menuItemTreinosAtivos = new javax.swing.JMenuItem();
        menuItemTreinosInativos = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        menuItemSair = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setForeground(java.awt.Color.white);
        setPreferredSize(new java.awt.Dimension(1000, 430));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(""), "Menu Rapido", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("sansserif", 1, 13))); // NOI18N

        btnPagamento.setText("Controle de Pagamento");

        btnTreinosInativos.setText("Treinos Ativos");

        btnTreinos.setText("Gerenciar Treinos");

        btnTreinosAtivos.setText("Treinos Inativos");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTreinosAtivos, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(64, 64, 64)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnTreinosInativos, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTreinos, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPagamento)
                    .addComponent(btnTreinos))
                .addGap(97, 97, 97)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTreinosAtivos)
                    .addComponent(btnTreinosInativos))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        menuCadastro.setText("Cadastros");

        menuItemAluno.setText("Aluno");
        menuCadastro.add(menuItemAluno);

        menuItemProfessor.setText("Professor");
        menuCadastro.add(menuItemProfessor);

        jMenuBar1.add(menuCadastro);

        menuTreinos.setText("Treinos");

        menuItemTreinos.setText("Gerenciar Treinos");
        menuTreinos.add(menuItemTreinos);

        jMenuBar1.add(menuTreinos);

        menuPagamento.setText("Pagamento");

        menuItemPagamentos.setText("Controle de Pagamento");
        menuItemPagamentos.addActionListener(this::menuItemPagamentosActionPerformed);
        menuPagamento.add(menuItemPagamentos);

        jMenuBar1.add(menuPagamento);

        menuRelatorios.setText("Relatórios");

        menuItemTreinosAtivos.setText("Treinos Ativos");
        menuItemTreinosAtivos.addActionListener(this::menuItemTreinosAtivosActionPerformed);
        menuRelatorios.add(menuItemTreinosAtivos);

        menuItemTreinosInativos.setText("Treinos Inativos");
        menuRelatorios.add(menuItemTreinosInativos);

        jMenuBar1.add(menuRelatorios);

        jMenu1.setText("Sair");
        jMenu1.addActionListener(this::jMenu1ActionPerformed);

        menuItemSair.setText("Sair do Programa");
        menuItemSair.addActionListener(this::menuItemSairActionPerformed);
        jMenu1.add(menuItemSair);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(222, 222, 222)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(244, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(92, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuItemPagamentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemPagamentosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuItemPagamentosActionPerformed

    private void menuItemTreinosAtivosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemTreinosAtivosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuItemTreinosAtivosActionPerformed

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed

    }//GEN-LAST:event_jMenu1ActionPerformed

    private void menuItemSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemSairActionPerformed
        // TODO add your handling code here:
            int opc = JOptionPane.showConfirmDialog(
            this,
            "Deseja realmente sair?",
            "Confirmar saída",
            JOptionPane.YES_NO_OPTION
        );

        if (opc == JOptionPane.YES_OPTION) {
            System.exit(0);
        }

    }//GEN-LAST:event_menuItemSairActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TelaPrincipal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPagamento;
    private javax.swing.JButton btnTreinos;
    private javax.swing.JButton btnTreinosAtivos;
    private javax.swing.JButton btnTreinosInativos;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenu menuCadastro;
    private javax.swing.JMenuItem menuItemAluno;
    private javax.swing.JMenuItem menuItemPagamentos;
    private javax.swing.JMenuItem menuItemProfessor;
    private javax.swing.JMenuItem menuItemSair;
    private javax.swing.JMenuItem menuItemTreinos;
    private javax.swing.JMenuItem menuItemTreinosAtivos;
    private javax.swing.JMenuItem menuItemTreinosInativos;
    private javax.swing.JMenu menuPagamento;
    private javax.swing.JMenu menuRelatorios;
    private javax.swing.JMenu menuTreinos;
    // End of variables declaration//GEN-END:variables
}
