/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.proyetogrupo.proyetofinal.apresentacao;

/**
 *
 * @author pedro
 */
public class TelaTreinos extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaTreinos.class.getName());

    /**
     * Creates new form TelaTreinos1
     */
    public TelaTreinos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelAluno = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        comboAluno = new javax.swing.JComboBox<>();
        btnCarregarTreinos = new javax.swing.JButton();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        panelAluno12 = new javax.swing.JPanel();
        jLabel123 = new javax.swing.JLabel();
        comboAluno12 = new javax.swing.JComboBox<>();
        btnCarregarTreinos12 = new javax.swing.JButton();
        jPanel30 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        comboProfessor22 = new javax.swing.JComboBox<>();
        jLabel124 = new javax.swing.JLabel();
        jScrollPane23 = new javax.swing.JScrollPane();
        txtDescricao22 = new javax.swing.JTextArea();
        jLabel125 = new javax.swing.JLabel();
        txtDataInicio22 = new javax.swing.JFormattedTextField();
        jLabel126 = new javax.swing.JLabel();
        txtDataFim22 = new javax.swing.JFormattedTextField();
        btnEntrar22 = new javax.swing.JButton();
        jLabel127 = new javax.swing.JLabel();
        jComboBox23 = new javax.swing.JComboBox<>();
        jPanel31 = new javax.swing.JPanel();
        tblTreinos7 = new javax.swing.JScrollPane();
        jTable8 = new javax.swing.JTable();
        btnDesativar7 = new javax.swing.JButton();

        panelAluno.setBorder(javax.swing.BorderFactory.createTitledBorder("Dados Aluno"));

        jLabel1.setText("Aluno");

        comboAluno.addActionListener(this::comboAlunoActionPerformed);

        btnCarregarTreinos.setText("Carregar treinos");

        javax.swing.GroupLayout panelAlunoLayout = new javax.swing.GroupLayout(panelAluno);
        panelAluno.setLayout(panelAlunoLayout);
        panelAlunoLayout.setHorizontalGroup(
            panelAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAlunoLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel1)
                .addGap(51, 51, 51)
                .addComponent(comboAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(btnCarregarTreinos)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelAlunoLayout.setVerticalGroup(
            panelAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAlunoLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(panelAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(comboAluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCarregarTreinos))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelAluno12.setBorder(javax.swing.BorderFactory.createTitledBorder("Dados Aluno"));

        jLabel123.setText("Aluno");

        comboAluno12.addActionListener(this::comboAluno12ActionPerformed);

        btnCarregarTreinos12.setText("Carregar treinos");

        javax.swing.GroupLayout panelAluno12Layout = new javax.swing.GroupLayout(panelAluno12);
        panelAluno12.setLayout(panelAluno12Layout);
        panelAluno12Layout.setHorizontalGroup(
            panelAluno12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAluno12Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel123)
                .addGap(51, 51, 51)
                .addComponent(comboAluno12, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(btnCarregarTreinos12)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelAluno12Layout.setVerticalGroup(
            panelAluno12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAluno12Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(panelAluno12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel123)
                    .addComponent(comboAluno12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCarregarTreinos12))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        jPanel30.setBorder(javax.swing.BorderFactory.createTitledBorder("Dados Treino"));

        jLabel2.setText("Professor:");

        jLabel124.setText("Descrição:");

        txtDescricao22.setColumns(20);
        txtDescricao22.setRows(5);
        jScrollPane23.setViewportView(txtDescricao22);

        jLabel125.setText("Data início:");

        txtDataInicio22.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd/MM/yy"))));

        jLabel126.setText("Data Fim:");

        txtDataFim22.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd/MM/yy"))));
        txtDataFim22.addActionListener(this::txtDataFim22ActionPerformed);

        btnEntrar22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Square-Tick@2x.png"))); // NOI18N
        btnEntrar22.setText("Salvar");
        btnEntrar22.addActionListener(this::btnEntrar22ActionPerformed);

        jLabel127.setText("Status do treino");

        jComboBox23.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ativo", "Inativo" }));

        javax.swing.GroupLayout jPanel30Layout = new javax.swing.GroupLayout(jPanel30);
        jPanel30.setLayout(jPanel30Layout);
        jPanel30Layout.setHorizontalGroup(
            jPanel30Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel30Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanel30Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel124)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel30Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(comboProfessor22, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane23, javax.swing.GroupLayout.DEFAULT_SIZE, 340, Short.MAX_VALUE))
                .addGap(121, 121, 121)
                .addGroup(jPanel30Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel30Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel30Layout.createSequentialGroup()
                            .addComponent(jLabel125)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtDataInicio22, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel30Layout.createSequentialGroup()
                            .addComponent(jLabel126)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(jPanel30Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtDataFim22)
                                .addGroup(jPanel30Layout.createSequentialGroup()
                                    .addGap(9, 9, 9)
                                    .addComponent(btnEntrar22)
                                    .addGap(0, 0, Short.MAX_VALUE)))))
                    .addGroup(jPanel30Layout.createSequentialGroup()
                        .addComponent(jLabel127)
                        .addGap(18, 18, 18)
                        .addComponent(jComboBox23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel30Layout.setVerticalGroup(
            jPanel30Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel30Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel30Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(comboProfessor22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel125)
                    .addComponent(txtDataInicio22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel30Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel124)
                    .addComponent(jScrollPane23, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel30Layout.createSequentialGroup()
                        .addGroup(jPanel30Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel126)
                            .addComponent(txtDataFim22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel30Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel127)
                            .addComponent(jComboBox23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnEntrar22)
                .addGap(52, 52, 52))
        );

        jPanel31.setBorder(javax.swing.BorderFactory.createTitledBorder("Tabela treinos"));

        jTable8.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "CPF", "Professor", "Status", "Data Início", "Data Fim", "Descrição"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblTreinos7.setViewportView(jTable8);

        btnDesativar7.setText("Desativar treino selecionado");
        btnDesativar7.addActionListener(this::btnDesativar7ActionPerformed);

        javax.swing.GroupLayout jPanel31Layout = new javax.swing.GroupLayout(jPanel31);
        jPanel31.setLayout(jPanel31Layout);
        jPanel31Layout.setHorizontalGroup(
            jPanel31Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel31Layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(tblTreinos7, javax.swing.GroupLayout.PREFERRED_SIZE, 1081, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel31Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnDesativar7)
                .addGap(436, 436, 436))
        );
        jPanel31Layout.setVerticalGroup(
            jPanel31Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel31Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(tblTreinos7, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addComponent(btnDesativar7)
                .addGap(53, 53, 53))
        );

        jDesktopPane1.setLayer(panelAluno12, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jPanel30, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jPanel31, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelAluno12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel30, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel31, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(panelAluno12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jPanel30, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel31, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comboAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboAlunoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboAlunoActionPerformed

    private void comboAluno12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboAluno12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboAluno12ActionPerformed

    private void txtDataFim22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDataFim22ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDataFim22ActionPerformed

    private void btnEntrar22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntrar22ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEntrar22ActionPerformed

    private void btnDesativar7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDesativar7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDesativar7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TelaTreinos().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCarregarTreinos;
    private javax.swing.JButton btnCarregarTreinos10;
    private javax.swing.JButton btnCarregarTreinos11;
    private javax.swing.JButton btnCarregarTreinos12;
    private javax.swing.JButton btnCarregarTreinos2;
    private javax.swing.JButton btnCarregarTreinos3;
    private javax.swing.JButton btnCarregarTreinos4;
    private javax.swing.JButton btnCarregarTreinos5;
    private javax.swing.JButton btnCarregarTreinos6;
    private javax.swing.JButton btnCarregarTreinos7;
    private javax.swing.JButton btnCarregarTreinos8;
    private javax.swing.JButton btnCarregarTreinos9;
    private javax.swing.JButton btnDesativar;
    private javax.swing.JButton btnDesativar1;
    private javax.swing.JButton btnDesativar2;
    private javax.swing.JButton btnDesativar3;
    private javax.swing.JButton btnDesativar4;
    private javax.swing.JButton btnDesativar5;
    private javax.swing.JButton btnDesativar6;
    private javax.swing.JButton btnDesativar7;
    private javax.swing.JButton btnEntrar;
    private javax.swing.JButton btnEntrar1;
    private javax.swing.JButton btnEntrar10;
    private javax.swing.JButton btnEntrar11;
    private javax.swing.JButton btnEntrar12;
    private javax.swing.JButton btnEntrar13;
    private javax.swing.JButton btnEntrar14;
    private javax.swing.JButton btnEntrar15;
    private javax.swing.JButton btnEntrar16;
    private javax.swing.JButton btnEntrar17;
    private javax.swing.JButton btnEntrar18;
    private javax.swing.JButton btnEntrar19;
    private javax.swing.JButton btnEntrar2;
    private javax.swing.JButton btnEntrar20;
    private javax.swing.JButton btnEntrar21;
    private javax.swing.JButton btnEntrar22;
    private javax.swing.JButton btnEntrar3;
    private javax.swing.JButton btnEntrar4;
    private javax.swing.JButton btnEntrar5;
    private javax.swing.JButton btnEntrar6;
    private javax.swing.JButton btnEntrar7;
    private javax.swing.JButton btnEntrar8;
    private javax.swing.JButton btnEntrar9;
    private javax.swing.JComboBox<String> comboAluno;
    private javax.swing.JComboBox<String> comboAluno10;
    private javax.swing.JComboBox<String> comboAluno11;
    private javax.swing.JComboBox<String> comboAluno12;
    private javax.swing.JComboBox<String> comboAluno2;
    private javax.swing.JComboBox<String> comboAluno3;
    private javax.swing.JComboBox<String> comboAluno4;
    private javax.swing.JComboBox<String> comboAluno5;
    private javax.swing.JComboBox<String> comboAluno6;
    private javax.swing.JComboBox<String> comboAluno7;
    private javax.swing.JComboBox<String> comboAluno8;
    private javax.swing.JComboBox<String> comboAluno9;
    private javax.swing.JComboBox<String> comboProfessor;
    private javax.swing.JComboBox<String> comboProfessor1;
    private javax.swing.JComboBox<String> comboProfessor10;
    private javax.swing.JComboBox<String> comboProfessor11;
    private javax.swing.JComboBox<String> comboProfessor12;
    private javax.swing.JComboBox<String> comboProfessor13;
    private javax.swing.JComboBox<String> comboProfessor14;
    private javax.swing.JComboBox<String> comboProfessor15;
    private javax.swing.JComboBox<String> comboProfessor16;
    private javax.swing.JComboBox<String> comboProfessor17;
    private javax.swing.JComboBox<String> comboProfessor18;
    private javax.swing.JComboBox<String> comboProfessor19;
    private javax.swing.JComboBox<String> comboProfessor2;
    private javax.swing.JComboBox<String> comboProfessor20;
    private javax.swing.JComboBox<String> comboProfessor21;
    private javax.swing.JComboBox<String> comboProfessor22;
    private javax.swing.JComboBox<String> comboProfessor3;
    private javax.swing.JComboBox<String> comboProfessor4;
    private javax.swing.JComboBox<String> comboProfessor5;
    private javax.swing.JComboBox<String> comboProfessor6;
    private javax.swing.JComboBox<String> comboProfessor7;
    private javax.swing.JComboBox<String> comboProfessor8;
    private javax.swing.JComboBox<String> comboProfessor9;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox10;
    private javax.swing.JComboBox<String> jComboBox11;
    private javax.swing.JComboBox<String> jComboBox12;
    private javax.swing.JComboBox<String> jComboBox13;
    private javax.swing.JComboBox<String> jComboBox14;
    private javax.swing.JComboBox<String> jComboBox15;
    private javax.swing.JComboBox<String> jComboBox16;
    private javax.swing.JComboBox<String> jComboBox17;
    private javax.swing.JComboBox<String> jComboBox18;
    private javax.swing.JComboBox<String> jComboBox19;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox20;
    private javax.swing.JComboBox<String> jComboBox21;
    private javax.swing.JComboBox<String> jComboBox22;
    private javax.swing.JComboBox<String> jComboBox23;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JComboBox<String> jComboBox5;
    private javax.swing.JComboBox<String> jComboBox6;
    private javax.swing.JComboBox<String> jComboBox7;
    private javax.swing.JComboBox<String> jComboBox8;
    private javax.swing.JComboBox<String> jComboBox9;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel100;
    private javax.swing.JLabel jLabel101;
    private javax.swing.JLabel jLabel102;
    private javax.swing.JLabel jLabel103;
    private javax.swing.JLabel jLabel104;
    private javax.swing.JLabel jLabel105;
    private javax.swing.JLabel jLabel106;
    private javax.swing.JLabel jLabel107;
    private javax.swing.JLabel jLabel108;
    private javax.swing.JLabel jLabel109;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel110;
    private javax.swing.JLabel jLabel111;
    private javax.swing.JLabel jLabel112;
    private javax.swing.JLabel jLabel113;
    private javax.swing.JLabel jLabel114;
    private javax.swing.JLabel jLabel115;
    private javax.swing.JLabel jLabel116;
    private javax.swing.JLabel jLabel117;
    private javax.swing.JLabel jLabel118;
    private javax.swing.JLabel jLabel119;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel120;
    private javax.swing.JLabel jLabel121;
    private javax.swing.JLabel jLabel122;
    private javax.swing.JLabel jLabel123;
    private javax.swing.JLabel jLabel124;
    private javax.swing.JLabel jLabel125;
    private javax.swing.JLabel jLabel126;
    private javax.swing.JLabel jLabel127;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JLabel jLabel66;
    private javax.swing.JLabel jLabel67;
    private javax.swing.JLabel jLabel68;
    private javax.swing.JLabel jLabel69;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel70;
    private javax.swing.JLabel jLabel71;
    private javax.swing.JLabel jLabel72;
    private javax.swing.JLabel jLabel73;
    private javax.swing.JLabel jLabel74;
    private javax.swing.JLabel jLabel75;
    private javax.swing.JLabel jLabel76;
    private javax.swing.JLabel jLabel77;
    private javax.swing.JLabel jLabel78;
    private javax.swing.JLabel jLabel79;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel80;
    private javax.swing.JLabel jLabel81;
    private javax.swing.JLabel jLabel82;
    private javax.swing.JLabel jLabel83;
    private javax.swing.JLabel jLabel84;
    private javax.swing.JLabel jLabel85;
    private javax.swing.JLabel jLabel86;
    private javax.swing.JLabel jLabel87;
    private javax.swing.JLabel jLabel88;
    private javax.swing.JLabel jLabel89;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel90;
    private javax.swing.JLabel jLabel91;
    private javax.swing.JLabel jLabel92;
    private javax.swing.JLabel jLabel93;
    private javax.swing.JLabel jLabel94;
    private javax.swing.JLabel jLabel95;
    private javax.swing.JLabel jLabel96;
    private javax.swing.JLabel jLabel97;
    private javax.swing.JLabel jLabel98;
    private javax.swing.JLabel jLabel99;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanel24;
    private javax.swing.JPanel jPanel25;
    private javax.swing.JPanel jPanel26;
    private javax.swing.JPanel jPanel27;
    private javax.swing.JPanel jPanel28;
    private javax.swing.JPanel jPanel29;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel30;
    private javax.swing.JPanel jPanel31;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane12;
    private javax.swing.JScrollPane jScrollPane13;
    private javax.swing.JScrollPane jScrollPane14;
    private javax.swing.JScrollPane jScrollPane15;
    private javax.swing.JScrollPane jScrollPane16;
    private javax.swing.JScrollPane jScrollPane17;
    private javax.swing.JScrollPane jScrollPane18;
    private javax.swing.JScrollPane jScrollPane19;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane20;
    private javax.swing.JScrollPane jScrollPane21;
    private javax.swing.JScrollPane jScrollPane22;
    private javax.swing.JScrollPane jScrollPane23;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTable jTable4;
    private javax.swing.JTable jTable5;
    private javax.swing.JTable jTable6;
    private javax.swing.JTable jTable7;
    private javax.swing.JTable jTable8;
    private javax.swing.JPanel panelAluno;
    private javax.swing.JPanel panelAluno10;
    private javax.swing.JPanel panelAluno11;
    private javax.swing.JPanel panelAluno12;
    private javax.swing.JPanel panelAluno2;
    private javax.swing.JPanel panelAluno3;
    private javax.swing.JPanel panelAluno4;
    private javax.swing.JPanel panelAluno5;
    private javax.swing.JPanel panelAluno6;
    private javax.swing.JPanel panelAluno7;
    private javax.swing.JPanel panelAluno8;
    private javax.swing.JPanel panelAluno9;
    private javax.swing.JScrollPane tblTreinos;
    private javax.swing.JScrollPane tblTreinos1;
    private javax.swing.JScrollPane tblTreinos2;
    private javax.swing.JScrollPane tblTreinos3;
    private javax.swing.JScrollPane tblTreinos4;
    private javax.swing.JScrollPane tblTreinos5;
    private javax.swing.JScrollPane tblTreinos6;
    private javax.swing.JScrollPane tblTreinos7;
    private javax.swing.JFormattedTextField txtDataFim;
    private javax.swing.JFormattedTextField txtDataFim1;
    private javax.swing.JFormattedTextField txtDataFim10;
    private javax.swing.JFormattedTextField txtDataFim11;
    private javax.swing.JFormattedTextField txtDataFim12;
    private javax.swing.JFormattedTextField txtDataFim13;
    private javax.swing.JFormattedTextField txtDataFim14;
    private javax.swing.JFormattedTextField txtDataFim15;
    private javax.swing.JFormattedTextField txtDataFim16;
    private javax.swing.JFormattedTextField txtDataFim17;
    private javax.swing.JFormattedTextField txtDataFim18;
    private javax.swing.JFormattedTextField txtDataFim19;
    private javax.swing.JFormattedTextField txtDataFim2;
    private javax.swing.JFormattedTextField txtDataFim20;
    private javax.swing.JFormattedTextField txtDataFim21;
    private javax.swing.JFormattedTextField txtDataFim22;
    private javax.swing.JFormattedTextField txtDataFim3;
    private javax.swing.JFormattedTextField txtDataFim4;
    private javax.swing.JFormattedTextField txtDataFim5;
    private javax.swing.JFormattedTextField txtDataFim6;
    private javax.swing.JFormattedTextField txtDataFim7;
    private javax.swing.JFormattedTextField txtDataFim8;
    private javax.swing.JFormattedTextField txtDataFim9;
    private javax.swing.JFormattedTextField txtDataInicio;
    private javax.swing.JFormattedTextField txtDataInicio1;
    private javax.swing.JFormattedTextField txtDataInicio10;
    private javax.swing.JFormattedTextField txtDataInicio11;
    private javax.swing.JFormattedTextField txtDataInicio12;
    private javax.swing.JFormattedTextField txtDataInicio13;
    private javax.swing.JFormattedTextField txtDataInicio14;
    private javax.swing.JFormattedTextField txtDataInicio15;
    private javax.swing.JFormattedTextField txtDataInicio16;
    private javax.swing.JFormattedTextField txtDataInicio17;
    private javax.swing.JFormattedTextField txtDataInicio18;
    private javax.swing.JFormattedTextField txtDataInicio19;
    private javax.swing.JFormattedTextField txtDataInicio2;
    private javax.swing.JFormattedTextField txtDataInicio20;
    private javax.swing.JFormattedTextField txtDataInicio21;
    private javax.swing.JFormattedTextField txtDataInicio22;
    private javax.swing.JFormattedTextField txtDataInicio3;
    private javax.swing.JFormattedTextField txtDataInicio4;
    private javax.swing.JFormattedTextField txtDataInicio5;
    private javax.swing.JFormattedTextField txtDataInicio6;
    private javax.swing.JFormattedTextField txtDataInicio7;
    private javax.swing.JFormattedTextField txtDataInicio8;
    private javax.swing.JFormattedTextField txtDataInicio9;
    private javax.swing.JTextArea txtDescricao;
    private javax.swing.JTextArea txtDescricao1;
    private javax.swing.JTextArea txtDescricao10;
    private javax.swing.JTextArea txtDescricao11;
    private javax.swing.JTextArea txtDescricao12;
    private javax.swing.JTextArea txtDescricao13;
    private javax.swing.JTextArea txtDescricao14;
    private javax.swing.JTextArea txtDescricao15;
    private javax.swing.JTextArea txtDescricao16;
    private javax.swing.JTextArea txtDescricao17;
    private javax.swing.JTextArea txtDescricao18;
    private javax.swing.JTextArea txtDescricao19;
    private javax.swing.JTextArea txtDescricao2;
    private javax.swing.JTextArea txtDescricao20;
    private javax.swing.JTextArea txtDescricao21;
    private javax.swing.JTextArea txtDescricao22;
    private javax.swing.JTextArea txtDescricao3;
    private javax.swing.JTextArea txtDescricao4;
    private javax.swing.JTextArea txtDescricao5;
    private javax.swing.JTextArea txtDescricao6;
    private javax.swing.JTextArea txtDescricao7;
    private javax.swing.JTextArea txtDescricao8;
    private javax.swing.JTextArea txtDescricao9;
    // End of variables declaration//GEN-END:variables
}
